from .vgg import *
from .resnet import *
from .densenet import *
from .MixNet import *
from .EfficientNet import *
from .SqueezeNext import *
from .SqueezeNet import *
from .MobileNet import *
from .MobileNetV2 import *
from .MobileNetV3 import *
from .ShuffleNet import *
from .ShuffleNetV2 import *
from .IGCV1 import *
from .IGCV3 import *
from .Pelee import *
from .AntCNN import *
from .AntGCNN import *
from .eXnet import *
from .FerNet import *
from .SVGG import *
